import { runTestSuite } from '../test-runner.js';

const PUBLIC_INTEREST_ACCOUNT_ID = 'acc-interest-public';

function bootstrapTestEnv() {
  process.env.NODE_ENV = process.env.NODE_ENV || 'test';
  process.env.PUBLIC_INTEREST_ACCOUNT_ID = process.env.PUBLIC_INTEREST_ACCOUNT_ID || PUBLIC_INTEREST_ACCOUNT_ID;
}

bootstrapTestEnv();

const [
  auth,
  rbac,
  supabaseMembership,
  validation,
  publicRoutes,
  cors,
  payloadLimit,
  scopes,
  clientesRepository,
  clientesPagination,
  clientesTenant,
  clientesRlsContract,
  produtosRepository,
  produtosPagination,
  produtosTenant,
  produtosSearch,
  produtoImagens,
  pedidosRepository,
  pedidosPagination,
  pedidosTenant,
  pedidosCreateRbac,
  pedidosCalculation,
  pedidosStatus,
  pedidosStatusUpdate,
  pedidosStatusRules,
  pedidosAudit,
  pedidosItensUpdate,
  pedidosUpdate,
  analyticsSummary,
  analyticsProducts,
  analyticsCustomers,
  analyticsPeriods,
  analyticsTenant,
  analyticsDateValidation,
  commercialOwnership,
  interestLeadsCreate,
  interestLeadsValidation,
  interestLeadsList,
  interestLeadsStatus,
  interestLeadsExport,
  interestLeadsDashboard,
  interestLeadsEvents,
  interestLeadsRepository,
  interestLeadsInvite,
  interestLeadsBulkBatch,
  interestLeadsLaunchDashboard,
  interestLeadsConvert,
  launchTemplates,
  launchPreview,
  launchQueue,
  onboardingStart,
  onboardingStep,
  onboardingComplete,
  jornadaComercialE2E,
  leadToAccountTrial,
  billingOnboardingIntegration,
  accountActivationStatus,
  implementationStatus,
  customerSuccess,
  customerSuccessAutomation,
  customerSuccessTimeline,
  portfolioDashboard,
  executivePortfolioAnalytics,
  fabricantes,
  fabricantesTenant,
  legacyImport,
  legacyImportStaging,
  legacyImportApproval,
  legacyImportPromotion,
  customerMemory,
  whatsappContext,
  whatsappConversations,
  whatsappDraftState,
  messageDrafts,
  actionAwareDrafts,
  messageApprovals,
  whatsappDelivery,
  commercialAgent,
  approvalIntelligence,
  productAudit,
  produtosImport,
  productEditor,
  vendedores,
  clientesVendedorScope,
  auditLogs
] = await Promise.all([
  import('./auth.test.js'),
  import('./rbac.test.js'),
  import('./supabase-membership.test.js'),
  import('./validation.test.js'),
  import('./public-routes.test.js'),
  import('./cors.test.js'),
  import('./payload-limit.test.js'),
  import('./scopes.test.js'),
  import('./clientes-repository.test.js'),
  import('./clientes-pagination.test.js'),
  import('./clientes-tenant.test.js'),
  import('./clientes-rls-contract.test.js'),
  import('./produtos-repository.test.js'),
  import('./produtos-pagination.test.js'),
  import('./produtos-tenant.test.js'),
  import('./produtos-search.test.js'),
  import('./produto-imagens.test.js'),
  import('./pedidos-repository.test.js'),
  import('./pedidos-pagination.test.js'),
  import('./pedidos-tenant.test.js'),
  import('./pedidos-create-rbac.test.js'),
  import('./pedidos-calculation.test.js'),
  import('./pedidos-status.test.js'),
  import('./pedidos-status-update.test.js'),
  import('./pedidos-status-rules.test.js'),
  import('./pedidos-audit.test.js'),
  import('./pedidos-itens-update.test.js'),
  import('./pedidos-update.test.js'),
  import('./analytics-summary.test.js'),
  import('./analytics-products.test.js'),
  import('./analytics-customers.test.js'),
  import('./analytics-periods.test.js'),
  import('./analytics-tenant.test.js'),
  import('./analytics-date-validation.test.js'),
  import('./commercial-ownership.test.js'),
  import('./interest-leads-create.test.js'),
  import('./interest-leads-validation.test.js'),
  import('./interest-leads-list.test.js'),
  import('./interest-leads-status.test.js'),
  import('./interest-leads-export.test.js'),
  import('./interest-leads-dashboard.test.js'),
  import('./interest-leads-events.test.js'),
  import('./interest-leads-repository.test.js'),
  import('./interest-leads-invite.test.js'),
  import('./interest-leads-bulk-batch.test.js'),
  import('./interest-leads-launch-dashboard.test.js'),
  import('./interest-leads-convert.test.js'),
  import('./launch-templates.test.js'),
  import('./launch-preview.test.js'),
  import('./launch-queue.test.js'),
  import('./onboarding-start.test.js'),
  import('./onboarding-step.test.js'),
  import('./onboarding-complete.test.js'),
  import('./jornada-comercial-e2e.test.js'),
  import('./lead-to-account-trial.test.js'),
  import('./billing-onboarding-integration.test.js'),
  import('./account-activation-status.test.js'),
  import('./implementation-status.test.js'),
  import('./customer-success.test.js'),
  import('./customer-success-automation.test.js'),
  import('./customer-success-timeline.test.js'),
  import('./portfolio-dashboard.test.js'),
  import('./executive-portfolio-analytics.test.js'),
  import('./fabricantes.test.js'),
  import('./fabricantes-tenant.test.js'),
  import('./legacy-import.test.js'),
  import('./legacy-import-staging.test.js'),
  import('./legacy-import-approval.test.js'),
  import('./legacy-import-promotion.test.js'),
  import('./customer-memory.test.js'),
  import('./whatsapp-context.test.js'),
  import('./whatsapp-conversations.test.js'),
  import('./whatsapp-draft-state.test.js'),
  import('./message-drafts.test.js'),
  import('./action-aware-drafts.test.js'),
  import('./message-approvals.test.js'),
  import('./whatsapp-delivery.test.js'),
  import('./commercial-agent.test.js'),
  import('./approval-intelligence.test.js'),
  import('./product-audit.test.js'),
  import('./produtos-import.test.js'),
  import('./product-editor.test.js'),
  import('./vendedores.test.js'),
  import('./clientes-vendedor-scope.test.js'),
  import('./audit-logs.test.js')
]);

async function main() {
  const suites = [
    ['Auth', auth.getAuthTests()],
    ['RBAC', rbac.getRbacTests()],
    ['Supabase Membership', supabaseMembership.getSupabaseMembershipTests()],
    ['Validation', validation.getValidationTests()],
    ['Public Routes', publicRoutes.getPublicRouteTests()],
    ['CORS', cors.getCorsTests()],
    ['Payload Limit', payloadLimit.getPayloadLimitTests()],
    ['Scopes', scopes.getScopesTests()],
    ['Clientes Repository', clientesRepository.getClientesRepositoryTests()],
    ['Clientes Pagination', clientesPagination.getClientesPaginationTests()],
    ['Clientes Tenant', clientesTenant.getClientesTenantTests()],
    ['Clientes RLS Contract', clientesRlsContract.getClientesRlsContractTests()],
    ['Produtos Repository', produtosRepository.getProdutosRepositoryTests()],
    ['Produtos Pagination', produtosPagination.getProdutosPaginationTests()],
    ['Produtos Tenant', produtosTenant.getProdutosTenantTests()],
    ['Produtos Search', produtosSearch.getProdutosSearchTests()],
    ['Produto Imagens', produtoImagens.getProdutoImagensTests()],
    ['Pedidos Repository', pedidosRepository.getPedidosRepositoryTests()],
    ['Pedidos Pagination', pedidosPagination.getPedidosPaginationTests()],
    ['Pedidos Tenant', pedidosTenant.getPedidosTenantTests()],
    ['Pedidos Create RBAC', pedidosCreateRbac.getPedidosCreateRbacTests()],
    ['Pedidos Calculation', pedidosCalculation.getPedidosCalculationTests()],
    ['Pedidos Status', pedidosStatus.getPedidosStatusTests()],
    ['Pedidos Status Update', pedidosStatusUpdate.getPedidosStatusUpdateTests()],
    ['Pedidos Status Rules', pedidosStatusRules.getPedidosStatusRulesTests()],
    ['Pedidos Audit', pedidosAudit.getPedidosAuditTests()],
    ['Pedidos Itens Update', pedidosItensUpdate.getPedidosItensUpdateTests()],
    ['Pedidos Update', pedidosUpdate.getPedidosUpdateTests()],
    ['Analytics Summary', analyticsSummary.getAnalyticsSummaryTests()],
    ['Analytics Products', analyticsProducts.getAnalyticsProductsTests()],
    ['Analytics Customers', analyticsCustomers.getAnalyticsCustomersTests()],
    ['Analytics Periods', analyticsPeriods.getAnalyticsPeriodsTests()],
    ['Analytics Tenant', analyticsTenant.getAnalyticsTenantTests()],
    ['Analytics Date Validation', analyticsDateValidation.getAnalyticsDateValidationTests()],
    ['Commercial Ownership', commercialOwnership.getCommercialOwnershipTests()],
    ['Interest Leads Create', interestLeadsCreate.getInterestLeadsCreateTests()],
    ['Interest Leads Validation', interestLeadsValidation.getInterestLeadsValidationTests()],
    ['Interest Leads List', interestLeadsList.getInterestLeadsListTests()],
    ['Interest Leads Status', interestLeadsStatus.getInterestLeadsStatusTests()],
    ['Interest Leads Export', interestLeadsExport.getInterestLeadsExportTests()],
    ['Interest Leads Dashboard', interestLeadsDashboard.getInterestLeadsDashboardTests()],
    ['Interest Leads Events', interestLeadsEvents.getInterestLeadsEventsTests()],
    ['Interest Leads Repository', interestLeadsRepository.getInterestLeadsRepositoryTests()],
    ['Interest Leads Invite', interestLeadsInvite.getInterestLeadsInviteTests()],
    ['Interest Leads Bulk Batch', interestLeadsBulkBatch.getInterestLeadsBulkBatchTests()],
    ['Interest Leads Launch Dashboard', interestLeadsLaunchDashboard.getInterestLeadsLaunchDashboardTests()],
    ['Interest Leads Convert', interestLeadsConvert.getInterestLeadsConvertTests()],
    ['Launch Templates', launchTemplates.getLaunchTemplatesTests()],
    ['Launch Preview', launchPreview.getLaunchPreviewTests()],
    ['Launch Queue', launchQueue.getLaunchQueueTests()],
    ['Onboarding Start', onboardingStart.getOnboardingStartTests()],
    ['Onboarding Step', onboardingStep.getOnboardingStepTests()],
    ['Onboarding Complete', onboardingComplete.getOnboardingCompleteTests()],
    ['Account Activation Status', accountActivationStatus.getAccountActivationStatusTests()],
    ['Implementation Status', implementationStatus.getImplementationStatusTests()],
    ['Customer Success', customerSuccess.getCustomerSuccessTests()],
    ['Customer Success Automation', customerSuccessAutomation.getCustomerSuccessAutomationTests()],
    ['Customer Success Timeline', customerSuccessTimeline.getCustomerSuccessTimelineTests()],
    ['Customer Memory', customerMemory.getCustomerMemoryTests()],
    ['WhatsApp Context', whatsappContext.getWhatsappContextTests()],
    ['WhatsApp Conversations', whatsappConversations.getWhatsappConversationsTests()],
    ['WhatsApp Draft State', whatsappDraftState.getWhatsappDraftStateTests()],
    ['Message Drafts', messageDrafts.getMessageDraftsTests()],
    ['Action Aware Drafts', actionAwareDrafts.getActionAwareDraftsTests()],
    ['Message Approvals', messageApprovals.getMessageApprovalsTests()],
    ['WhatsApp Delivery', whatsappDelivery.getWhatsappDeliveryTests()],
    ['Commercial Agent', commercialAgent.getCommercialAgentTests()],
    ['Approval Intelligence', approvalIntelligence.getApprovalIntelligenceTests()],
    ['Portfolio Dashboard', portfolioDashboard.getPortfolioDashboardTests()],
    ['Legacy Import', legacyImport.getLegacyImportTests()],
    ['Legacy Import Staging', legacyImportStaging.getLegacyImportStagingTests()],
    ['Legacy Import Approval', legacyImportApproval.getLegacyImportApprovalTests()],
    ['Legacy Import Promotion', legacyImportPromotion.getLegacyImportPromotionTests()],
    ['Jornada Comercial E2E', jornadaComercialE2E.getJornadaComercialE2ETests()],
    ['Lead to Account Trial', leadToAccountTrial.getLeadToAccountTrialTests()],
    ['Billing Onboarding Integration', billingOnboardingIntegration.getBillingOnboardingIntegrationTests()],
    ['Executive Portfolio Analytics', executivePortfolioAnalytics.getExecutivePortfolioAnalyticsTests()],
    ['Fabricantes', fabricantes.getFabricantesTests()],
    ['Fabricantes Tenant', fabricantesTenant.getFabricantesTenantTests()],
    ['Product Audit', productAudit.getProductAuditTests()],
    ['Produtos Import', produtosImport.getProdutosImportTests()],
    ['Product Editor', productEditor.getProductEditorTests()],
    ['Vendedores', vendedores.getVendedoresTests()],
    ['Clientes Vendedor Scope', clientesVendedorScope.getClientesVendedorScopeTests()]
    ,['Audit Logs', auditLogs.getAuditLogsTests()]
  ];

  const summary = { total: 0, passed: 0, failed: 0 };
  for (const [name, tests] of suites) {
    const result = await runTestSuite(name, tests);
    summary.total += result.total;
    summary.passed += result.passed;
    summary.failed += result.failed;
  }

  console.log('\n=== API Test Summary ===');
  console.log(`Total: ${summary.total}`);
  console.log(`Passed: ${summary.passed}`);
  console.log(`Failed: ${summary.failed}`);
  if (summary.failed > 0) process.exitCode = 1;
}

main();
