import assert from 'node:assert/strict';
import { createCliente, __resetMemoryClientesForTests } from '../../modules/clientes/clientes.repository.js';
import { createConversation, __resetMemoryWhatsappConversationsForTests, listEvents } from '../../modules/whatsapp-conversations/whatsapp-conversations.repository.js';
import { generateMessageDraftHandler } from '../../modules/message-drafts/message-drafts.controller.js';
import { getMessageDraftById, __resetMemoryMessageDraftsForTests } from '../../modules/message-drafts/message-drafts.repository.js';
import { approveMessageDraftHandler, rejectMessageDraftHandler, listPendingMessageApprovalsHandler, listMessageApprovalsHandler, getMessageApprovalHandler } from '../../modules/message-approvals/message-approvals.controller.js';
import { __resetMemoryMessageApprovalsForTests } from '../../modules/message-approvals/message-approvals.repository.js';

function resetState() { __resetMemoryClientesForTests(); __resetMemoryWhatsappConversationsForTests(); __resetMemoryMessageDraftsForTests(); __resetMemoryMessageApprovalsForTests(); }

export function getMessageApprovalsTests() {
  return [
    { name: 'aprovação', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente A' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999999', clienteId: cliente.id }, { accountId: 'acc-a' }); const draft = await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); const result = await approveMessageDraftHandler({ accountId: 'acc-a', auth: { role: 'manager', userId: 'u1', name: 'Manager' }, params: { draftId: draft.draftId }, body: { comment: '' } }); assert.equal(result.item.status, 'approved'); const stored = await getMessageDraftById(draft.draftId, { accountId: 'acc-a' }); assert.equal(stored.status, 'approved'); const events = await listEvents(conv.id, { accountId: 'acc-a' }); assert.equal(events.some((event) => event.type === 'draft_generated'), true); assert.equal(events.some((event) => event.type === 'draft_approved'), true); } },
    { name: 'rejeição', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente B' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999998', clienteId: cliente.id }, { accountId: 'acc-a' }); const draft = await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); const result = await rejectMessageDraftHandler({ accountId: 'acc-a', auth: { role: 'manager', userId: 'u1', name: 'Manager' }, params: { draftId: draft.draftId }, body: { comment: 'Não enviar' } }); assert.equal(result.item.status, 'rejected'); } },
    { name: 'comentário obrigatório', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente C' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999997', clienteId: cliente.id }, { accountId: 'acc-a' }); const draft = await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); await assert.rejects(() => rejectMessageDraftHandler({ accountId: 'acc-a', auth: { role: 'manager' }, params: { draftId: draft.draftId }, body: { comment: '' } })); } },
    { name: 'tenant isolation', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente D' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999996', clienteId: cliente.id }, { accountId: 'acc-a' }); const draft = await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); await assert.rejects(() => approveMessageDraftHandler({ accountId: 'acc-b', auth: { role: 'manager' }, params: { draftId: draft.draftId }, body: { comment: '' } })); } },
    { name: 'role validation', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente E' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999995', clienteId: cliente.id }, { accountId: 'acc-a' }); const draft = await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); await assert.rejects(() => approveMessageDraftHandler({ accountId: 'acc-a', auth: { role: 'sales' }, params: { draftId: draft.draftId }, body: { comment: '' } })); } },
    { name: 'atualização do draft', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente F' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999994', clienteId: cliente.id }, { accountId: 'acc-a' }); const draft = await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); await approveMessageDraftHandler({ accountId: 'acc-a', auth: { role: 'manager' }, params: { draftId: draft.draftId }, body: { comment: '' } }); const pending = await listPendingMessageApprovalsHandler({ accountId: 'acc-a' }); assert.equal(pending.items.length, 0); } },
    { name: 'criação auditoria', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente G' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999993', clienteId: cliente.id }, { accountId: 'acc-a' }); const draft = await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); await approveMessageDraftHandler({ accountId: 'acc-a', auth: { role: 'manager', userId: 'u1', name: 'Manager' }, params: { draftId: draft.draftId }, body: { comment: '' } }); const events = await listEvents(conv.id, { accountId: 'acc-a' }); assert.equal(events.some((event) => event.type === 'draft_approved'), true); } },
    { name: 'listagem pending', run: async () => { resetState(); const cliente = await createCliente({ nome: 'Cliente H' }, { accountId: 'acc-a' }); const conv = await createConversation({ phone: '11999999992', clienteId: cliente.id }, { accountId: 'acc-a' }); await generateMessageDraftHandler({ accountId: 'acc-a', body: { conversationId: conv.id } }); const pending = await listPendingMessageApprovalsHandler({ accountId: 'acc-a' }); assert.equal(Array.isArray(pending.items), true); const list = await listMessageApprovalsHandler({ accountId: 'acc-a' }); assert.equal(Array.isArray(list.items), true); } }
  ];
}
