import assert from 'node:assert/strict';
import { createConversation, addMessage, updateConversationStatus, addEvent, listConversations, getConversationDetail, __resetMemoryWhatsappConversationsForTests } from '../../modules/whatsapp-conversations/whatsapp-conversations.repository.js';

export function getWhatsappConversationsTests() {
  return [
    { name: 'cria conversa', run: async () => { __resetMemoryWhatsappConversationsForTests(); const item = await createConversation({ phone: '(11) 99999-9999', clienteId: 'cli-1', contactName: 'Ana' }, { accountId: 'acc-a' }); assert.equal(item.phone, '11999999999'); } },
    { name: 'lista conversas', run: async () => { __resetMemoryWhatsappConversationsForTests(); await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); const result = await listConversations({}, { accountId: 'acc-a' }); assert.equal(result.total, 1); } },
    { name: 'retorna conversa com mensagens', run: async () => { __resetMemoryWhatsappConversationsForTests(); const conv = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); await addMessage(conv.id, { direction: 'outbound', body: 'oi', senderType: 'agent', status: 'draft' }, { accountId: 'acc-a' }); const detail = await getConversationDetail(conv.id, { accountId: 'acc-a' }); assert.equal(detail.messages.length, 1); } },
    { name: 'evita duplicidade por phone + cliente', run: async () => { __resetMemoryWhatsappConversationsForTests(); const a = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); const b = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); assert.equal(a.id, b.id); } },
    { name: 'normaliza telefone', run: async () => { __resetMemoryWhatsappConversationsForTests(); const item = await createConversation({ phone: '+55 (11) 99999-9999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); assert.equal(item.phone, '5511999999999'); } },
    { name: 'ignora account_id malicioso', run: async () => { __resetMemoryWhatsappConversationsForTests(); await assert.rejects(() => createConversation({ phone: '11999999999', account_id: 'acc-x' }, { accountId: 'acc-a' })); } },
    { name: 'tenant isolation', run: async () => { __resetMemoryWhatsappConversationsForTests(); const item = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); await assert.rejects(() => getConversationDetail(item.id, { accountId: 'acc-b' })); } },
    { name: 'adiciona mensagem', run: async () => { __resetMemoryWhatsappConversationsForTests(); const conv = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); const msg = await addMessage(conv.id, { direction: 'inbound', body: 'ola', senderType: 'customer', status: 'received' }, { accountId: 'acc-a' }); assert.equal(msg.body, 'ola'); } },
    { name: 'nao envia mensagem externa', run: async () => { __resetMemoryWhatsappConversationsForTests(); const conv = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); const msg = await addMessage(conv.id, { direction: 'outbound', body: 'draft', senderType: 'agent', status: 'draft' }, { accountId: 'acc-a' }); assert.equal(msg.external_message_id, null); } },
    { name: 'altera status', run: async () => { __resetMemoryWhatsappConversationsForTests(); const conv = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); const updated = await updateConversationStatus(conv.id, 'closed', { accountId: 'acc-a' }); assert.equal(updated.status, 'closed'); } },
    { name: 'registra evento', run: async () => { __resetMemoryWhatsappConversationsForTests(); const conv = await createConversation({ phone: '11999999999', clienteId: 'cli-1' }, { accountId: 'acc-a' }); const evt = await addEvent(conv.id, { type: 'note_added', payload: { note: 'ok' } }, { accountId: 'acc-a' }); assert.equal(evt.type, 'note_added'); } },
    { name: 'paginação', run: async () => { __resetMemoryWhatsappConversationsForTests(); await createConversation({ phone: '111', clienteId: 'a' }, { accountId: 'acc-a' }); await createConversation({ phone: '222', clienteId: 'b' }, { accountId: 'acc-a' }); const result = await listConversations({ page: 1, limit: 1 }, { accountId: 'acc-a' }); assert.equal(result.items.length, 1); } },
    { name: 'filtros', run: async () => { __resetMemoryWhatsappConversationsForTests(); await createConversation({ phone: '111', clienteId: 'a' }, { accountId: 'acc-a' }); const result = await listConversations({ phone: '111' }, { accountId: 'acc-a' }); assert.equal(result.total, 1); } }
  ];
}
