import { createInterestLeadsState } from './interest-leads.state.js';

export function renderInterestLeadsPage(container, { apiClient }) {
  container.innerHTML = '<section><h1>Lista de Interesse Real</h1><p id="il-msg"></p><div><input id="il-search" placeholder="Buscar"><select id="il-status"><option value="">Todos</option><option value="novo">Novo</option><option value="contatado">Contatado</option><option value="qualificado">Qualificado</option><option value="descartado">Descartado</option></select><button id="il-load">Filtrar</button><a id="il-export" href="#">Exportar CSV</a></div><div id="il-root">Carregando...</div></section>';
  const state = createInterestLeadsState(apiClient); const root = container.querySelector('#il-root'); const msg = container.querySelector('#il-msg'); const searchEl = container.querySelector('#il-search'); const statusEl = container.querySelector('#il-status');
  async function load() { root.textContent = 'Carregando...'; msg.textContent=''; try { const filters = { search: searchEl.value.trim(), status: statusEl.value }; const data = await state.load(filters); container.querySelector('#il-export').href = state.exportCsvUrl(filters); if (!data.items.length) { root.textContent = 'Nenhum lead encontrado.'; return; } root.innerHTML = `<table><thead><tr><th>Nome</th><th>Empresa</th><th>Contato</th><th>Status</th><th>Ação</th></tr></thead><tbody>${data.items.map((i)=>`<tr><td>${i.nome}</td><td>${i.empresa}</td><td>${i.contato}</td><td>${i.status}</td><td><select data-id="${i.id}" class="il-status"><option ${i.status==='novo'?'selected':''}>novo</option><option ${i.status==='contatado'?'selected':''}>contatado</option><option ${i.status==='qualificado'?'selected':''}>qualificado</option><option ${i.status==='descartado'?'selected':''}>descartado</option></select></td></tr>`).join('')}</tbody></table>`; root.querySelectorAll('.il-status').forEach((el)=>{ el.addEventListener('change', async ()=>{ try { await state.updateStatus(el.getAttribute('data-id'), el.value); msg.textContent='Status atualizado com sucesso.'; } catch { msg.textContent='Erro ao atualizar status.'; } }); }); } catch { root.textContent = 'Erro ao carregar lista.'; } }
  container.querySelector('#il-load').onclick = load;
  load();
}
