export const envSchema = {
  NODE_ENV: { required: true, defaultValue: 'development', allowed: ['development', 'test', 'production'] },
  APP_ENV: { required: false, defaultValue: 'development', allowed: ['development', 'test', 'homologation', 'production'] },
  AUTH_MODE: { required: false, defaultValue: 'legacy', allowed: ['legacy', 'supabase'] },
  API_PORT: { required: false, defaultValue: '3000', type: 'number' },
  PORT: { required: false, defaultValue: '3000', type: 'number' },
  CORS_ORIGIN: { required: false, defaultValue: 'http://localhost:5173' },
  SUPABASE_URL: { required: false, defaultValue: '' },
  SUPABASE_SERVICE_ROLE_KEY: { required: false, defaultValue: '' },
  SUPABASE_ANON_KEY: { required: false, defaultValue: '' },
  PUBLIC_INTEREST_ACCOUNT_ID: { required: false, defaultValue: '' },
  INTEREST_LEADS_ACCOUNT_ID: { required: false, defaultValue: '' },
  COGNITIVE_WORKER_ENABLED: { required: false, defaultValue: 'false', allowed: ['true', 'false'] },
  COGNITIVE_PROVIDER: { required: false, defaultValue: 'disabled' },
  EMBEDDING_WORKER_ENABLED: { required: false, defaultValue: 'false', allowed: ['true', 'false'] },
  EMBEDDING_PROVIDER: { required: false, defaultValue: 'disabled' },
  WEB_DISCOVERY_ENABLED: { required: false, defaultValue: 'false', allowed: ['true', 'false'] },
  WEB_DISCOVERY_PROVIDERS: { required: false, defaultValue: 'brave,tavily' },
  BRAVE_SEARCH_API_KEY: { required: false, defaultValue: '' },
  TAVILY_API_KEY: { required: false, defaultValue: '' },
  WEB_DISCOVERY_MIN_CONFIDENCE: { required: false, defaultValue: '0.85', type: 'number' },
  ASAAS_ENV: { required: false, defaultValue: 'sandbox', allowed: ['sandbox', 'production'] },
  ASAAS_API_KEY: { required: false, defaultValue: '' },
  ASAAS_ALLOW_PRODUCTION: { required: false, defaultValue: 'false', allowed: ['true', 'false'] }
};
