alter table clientes
add column if not exists razao_social text,
add column if not exists nome_fantasia text,
add column if not exists cnae_principal text,
add column if not exists situacao_cadastral text,
add column if not exists data_abertura date,
add column if not exists cep text,
add column if not exists logradouro text,
add column if not exists numero text,
add column if not exists complemento text,
add column if not exists bairro text,
add column if not exists cidade text,
add column if not exists estado text,
add column if not exists email_enriquecido text,
add column if not exists telefone_enriquecido text,
add column if not exists enriquecimento_status text default 'pendente',
add column if not exists enriquecimento_ultima_execucao timestamptz,
add column if not exists enriquecimento_fonte text,
add column if not exists enriquecimento_erro text,
add column if not exists enriquecimento_payload jsonb default '{}'::jsonb;
