import { ValidationError } from '../../core/errors.js';
const FORBIDDEN_FIELDS = new Set(['account_id','accountId','tenant_id','tenantId','owner_user_id','ownerUserId']);
const STATUS = new Set(['novo','contatado','qualificado','aguardando_lancamento','convertido','perdido']);
const INVITE_STATUS = new Set(['nao_convidado','agendado','enviado','aberto','respondeu','convertido','cancelado']);
const BATCH = new Set(['lote-1','lote-2','lote-3']);
const TEMPLATE_CHANNEL = new Set(['email', 'whatsapp']);
const TEMPLATE_STATUS = new Set(['draft', 'active', 'archived']);
const cleanText=(v,m=120)=>String(v||'').trim().slice(0,m);
function assertNoSensitiveFields(payload){ for(const k of Object.keys(payload||{})){ if(FORBIDDEN_FIELDS.has(k)) throw new ValidationError(`Campo nao permitido: ${k}`);} }
export function normalizeCreateInterestLeadPayload(payload={}){assertNoSensitiveFields(payload);const nome=cleanText(payload.nome,120),empresa=cleanText(payload.empresa,120),whatsapp=cleanText(payload.whatsapp,40),email=cleanText(payload.email,160).toLowerCase();if(!nome) throw new ValidationError('Nome e obrigatorio.');if(!empresa) throw new ValidationError('Empresa e obrigatoria.');if(!whatsapp&&!email) throw new ValidationError('Informe WhatsApp ou E-mail.');return {nome,empresa,whatsapp,email,cidade:cleanText(payload.cidade,120),estado:cleanText(payload.estado,2).toUpperCase(),segmento:cleanText(payload.segmento,120),quantidade_vendedores:Math.max(0,Number.parseInt(payload.quantidade_vendedores??payload.quantidadeVendedores??'0',10)||0),origem:'landing-pre-lancamento',status:'novo',observacoes:'',responsavel:'',ultimo_contato_em:null,invite_status:'nao_convidado',launch_batch:null};}
export function normalizeListFilters(query={}){assertNoSensitiveFields(query);return {page:Math.max(1,Number.parseInt(String(query.page||'1'),10)||1),limit:Math.min(100,Math.max(1,Number.parseInt(String(query.limit||'20'),10)||20)),search:cleanText(query.search,120),status:cleanText(query.status,40),cidade:cleanText(query.cidade,120),segmento:cleanText(query.segmento,120),inviteStatus:cleanText(query.inviteStatus,40),launchBatch:cleanText(query.launchBatch,40),uf:cleanText(query.uf||query.estado,2).toUpperCase()};}
export function normalizeStatusPayload(payload={}){assertNoSensitiveFields(payload);const status=cleanText(payload.status,40);if(!STATUS.has(status)) throw new ValidationError('Status invalido.');return {status};}
export function normalizeLeadUpdatePayload(payload={}){assertNoSensitiveFields(payload);const out={};if(payload.status!==undefined) out.status=normalizeStatusPayload({status:payload.status}).status;if(payload.responsavel!==undefined) out.responsavel=cleanText(payload.responsavel,120);if(payload.ultimo_contato_em!==undefined) out.ultimo_contato_em=payload.ultimo_contato_em?String(payload.ultimo_contato_em):null;if(payload.invite_status!==undefined||payload.inviteStatus!==undefined){const s=cleanText(payload.invite_status??payload.inviteStatus,40);if(!INVITE_STATUS.has(s)) throw new ValidationError('Invite status invalido.');out.invite_status=s;}if(payload.launch_batch!==undefined||payload.launchBatch!==undefined){const b=cleanText(payload.launch_batch??payload.launchBatch,40);if(b && !BATCH.has(b)) throw new ValidationError('Launch batch invalido.');out.launch_batch=b||null;}return out;}
export function normalizeEventPayload(payload={}){assertNoSensitiveFields(payload);const tipo=cleanText(payload.tipo,60),descricao=cleanText(payload.descricao,500);if(!tipo) throw new ValidationError('Tipo e obrigatorio.');return {tipo,descricao};}
export function normalizeInvitePayload(payload={}){assertNoSensitiveFields(payload);const inviteStatus=cleanText(payload.inviteStatus??payload.invite_status,40);const launchBatch=cleanText(payload.launchBatch??payload.launch_batch,40);if(inviteStatus && !INVITE_STATUS.has(inviteStatus)) throw new ValidationError('Invite status invalido.');if(launchBatch && !BATCH.has(launchBatch)) throw new ValidationError('Launch batch invalido.');return {inviteStatus:inviteStatus||undefined,launchBatch:launchBatch||undefined};}
export function normalizeBulkLaunchBatchPayload(payload={}){assertNoSensitiveFields(payload);const leadIds=Array.isArray(payload.leadIds)?payload.leadIds.map((x)=>String(x||'').trim()).filter(Boolean):[];const launchBatch=cleanText(payload.launchBatch,40);if(!leadIds.length) throw new ValidationError('leadIds e obrigatorio.');if(!BATCH.has(launchBatch)) throw new ValidationError('Launch batch invalido.');return {leadIds,launchBatch};}
export function normalizeLaunchTemplatePayload(payload={}){assertNoSensitiveFields(payload);const channel=cleanText(payload.channel,20);const name=cleanText(payload.name,120);const subject=cleanText(payload.subject,200);const body=String(payload.body||'').trim();const status=cleanText(payload.status||'draft',20);if(!TEMPLATE_CHANNEL.has(channel)) throw new ValidationError('Canal invalido.');if(!name) throw new ValidationError('Nome e obrigatorio.');if(!body) throw new ValidationError('Body e obrigatorio.');if(!TEMPLATE_STATUS.has(status)) throw new ValidationError('Status invalido.');return {channel,name,subject,body,status};}
export function normalizePatchLaunchTemplatePayload(payload={}){assertNoSensitiveFields(payload);const out={}; if(payload.channel!==undefined){const channel=cleanText(payload.channel,20); if(!TEMPLATE_CHANNEL.has(channel)) throw new ValidationError('Canal invalido.'); out.channel=channel;} if(payload.name!==undefined) out.name=cleanText(payload.name,120); if(payload.subject!==undefined) out.subject=cleanText(payload.subject,200); if(payload.body!==undefined) out.body=String(payload.body||'').trim(); if(payload.status!==undefined){const status=cleanText(payload.status,20); if(!TEMPLATE_STATUS.has(status)) throw new ValidationError('Status invalido.'); out.status=status;} return out;}
export function normalizeLaunchPreviewPayload(payload={}){assertNoSensitiveFields(payload);const leadId=cleanText(payload.leadId,80);const templateId=cleanText(payload.templateId,80);if(!leadId||!templateId) throw new ValidationError('leadId e templateId sao obrigatorios.');return {leadId,templateId};}
export function normalizeLaunchQueuePayload(payload={}){assertNoSensitiveFields(payload);const leadIds=Array.isArray(payload.leadIds)?payload.leadIds.map((x)=>String(x||'').trim()).filter(Boolean):[];const templateId=cleanText(payload.templateId,80);if(!leadIds.length||!templateId) throw new ValidationError('leadIds e templateId sao obrigatorios.');return {leadIds,templateId};}
