import { asyncHandler } from '../../core/async-handler.js';
import { sendSuccess } from '../../core/response.js';
import { bulkLaunchBatchHandler, convertInterestLeadHandler, createInterestLeadEventHandler, createInterestLeadHandler, createLaunchTemplateHandler, deleteLaunchTemplateHandler, exportInterestLeadsCsvHandler, getInterestLeadHandler, getInterestLeadsDashboardHandler, getInterestLeadsLaunchDashboardHandler, launchPreviewHandler, launchQueueHandler, listInterestLeadEventsHandler, listInterestLeadsHandler, listLaunchTemplatesHandler, patchInterestLeadHandler, patchInterestLeadInviteHandler, patchInterestLeadStatusHandler, patchLaunchTemplateHandler } from './interest-leads.controller.js';
function esc(v) { return `"${String(v ?? '').replaceAll('"', '""')}"`; }
export function registerInterestLeadsRoutes(router) {
  router.registerRoute({ method: 'POST', path: '/interest-leads', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await createInterestLeadHandler(context)); })});
  router.registerRoute({ method: 'GET', path: '/interest-leads', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await listInterestLeadsHandler(context)); })});
  router.registerRoute({ method: 'GET', path: '/interest-leads/dashboard', domain: 'pre-lancamento', handler: asyncHandler(async (req,res)=>{ sendSuccess(res, await getInterestLeadsDashboardHandler()); })});
  router.registerRoute({ method: 'GET', path: '/interest-leads/launch-dashboard', domain: 'pre-lancamento', handler: asyncHandler(async (req,res)=>{ sendSuccess(res, await getInterestLeadsLaunchDashboardHandler()); })});
  router.registerRoute({ method: 'POST', path: '/interest-leads/bulk-launch-batch', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await bulkLaunchBatchHandler(context)); })});
  router.registerRoute({ method: 'GET', path: '/launch/templates', domain: 'pre-lancamento', handler: asyncHandler(async (req,res)=>{ sendSuccess(res, await listLaunchTemplatesHandler()); })});
  router.registerRoute({ method: 'POST', path: '/launch/templates', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await createLaunchTemplateHandler(context)); })});
  router.registerRoute({ method: 'PATCH', path: '/launch/templates/:id', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await patchLaunchTemplateHandler(context)); })});
  router.registerRoute({ method: 'DELETE', path: '/launch/templates/:id', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await deleteLaunchTemplateHandler(context)); })});
  router.registerRoute({ method: 'POST', path: '/launch/preview', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await launchPreviewHandler(context)); })});
  router.registerRoute({ method: 'POST', path: '/launch/queue', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await launchQueueHandler(context)); })});
  router.registerRoute({ method: 'GET', path: '/interest-leads/export.csv', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ const items = await exportInterestLeadsCsvHandler(context); const header = ['Nome','Empresa','WhatsApp','Email','Cidade','Estado','Segmento','Qtd Vendedores','Status','Origem','Data Cadastro']; const rows = items.map((i)=>[i.nome,i.empresa,i.whatsapp,i.email,i.cidade,i.estado,i.segmento,i.quantidade_vendedores,i.status,i.origem,i.created_at]); const csv = [header,...rows].map((r)=>r.map(esc).join(',')).join('\n'); res.statusCode = 200; res.setHeader('Content-Type','text/csv; charset=utf-8'); res.end(csv); })});
  router.registerRoute({ method: 'PATCH', path: '/interest-leads/:id/status', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await patchInterestLeadStatusHandler(context)); })});
  router.registerRoute({ method: 'PATCH', path: '/interest-leads/:id/invite', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await patchInterestLeadInviteHandler(context)); })});
  router.registerRoute({ method: 'POST', path: '/interest-leads/:id/convert', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await convertInterestLeadHandler(context)); })});
  router.registerRoute({ method: 'GET', path: '/interest-leads/:id/events', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await listInterestLeadEventsHandler(context)); })});
  router.registerRoute({ method: 'POST', path: '/interest-leads/:id/events', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await createInterestLeadEventHandler(context)); })});
  router.registerRoute({ method: 'GET', path: '/interest-leads/:id', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await getInterestLeadHandler(context)); })});
  router.registerRoute({ method: 'PATCH', path: '/interest-leads/:id', domain: 'pre-lancamento', handler: asyncHandler(async (req,res,context)=>{ sendSuccess(res, await patchInterestLeadHandler(context)); })});
}
